//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOHub.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSGOHub.Core.JsonResource", typeof(JsonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;provider&quot;: {
        ///                &quot;name&quot;: &quot;Counter-Strike: Global&quot;,
        ///                &quot;appid&quot;: 730,
        ///                &quot;version&quot;: 13512,
        ///                &quot;steamid&quot;: &quot;xadasdasd&quot;,
        ///                &quot;timestamp&quot;: 123123123
        ///        },
        ///        &quot;map&quot;: {
        ///                &quot;name&quot;: &quot;de_dust2&quot;,
        ///                &quot;phase&quot;: &quot;live&quot;,
        ///                &quot;round&quot;: 1,
        ///                &quot;team_ct&quot;: {
        ///                        &quot;name&quot;: &quot;Bonja&quot;,
        ///                        &quot;score&quot;: 0
        ///                },
        ///                &quot;team_t&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayloadExample {
            get {
                return ResourceManager.GetString("PayloadExample", resourceCulture);
            }
        }
    }
}
